version: '3.8'

services:
  api:
    container_name: sales_apis
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      -   8001:8001
    depends_on:
      - database

  database:
    container_name: sales_db
    image: mysql:8.0.11
    restart: always
    environment:
      MYSQL_DATABASE: sales_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql